[build]
  command = "rm -f yarn.lock && npm install --legacy-peer-deps --loglevel error && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_CONFIG_ENGINE_STRICT = "false"
  NPM_FLAGS = "--legacy-peer-deps"
